
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  r2dbc:
    url: r2dbc:postgresql://host.docker.internal:5432/postgres
    username: postgres
    password: postgres
logging:
  level:
    org.springframework.data.r2dbc: Debug