spring:
  data:
    mongodb:
      host: 127.0.0.1
      database: order
      port: 27017
  kafka:
    bootstrap-servers: localhost:9092
  integration:
    rsocket:
      server:
        message-mapping-enabled: true
server:
  port: 8079
